#!/bin/bash

echo "🚀 Setting up Production Environment Variables"
echo "============================================"
echo ""
echo "This script will help you set up the production environment variables."
echo ""
echo "STEP 1: Convex Production Environment Variables"
echo "------------------------------------------------"
echo "Go to: https://dashboard.convex.dev/d/artful-ibis-284/settings/environment-variables"
echo ""
echo "Add these environment variables:"
echo "  VOYAGE_API_KEY = pa-R02PH3qx5COlTDPTuKCoh2aQCsBsacXBrECRJGWZI_P"
echo "  PDFCO_API_KEY = will@w3dv.com_UnDe4pGi2JRUxuXJhPCJ5k21kdrbJaCyH7gwFcUMpo98Na0x86xHmPSLV4dApy8a"
echo ""
echo "Press Enter when you've added them to continue..."
read

echo ""
echo "STEP 2: Vercel Environment Variables"
echo "------------------------------------"
echo "If deploying to Vercel, add this in your project settings:"
echo "  NEXT_PUBLIC_CONVEX_URL = https://artful-ibis-284.convex.cloud"
echo ""
echo "To deploy to Vercel, run:"
echo "  vercel --prod"
echo ""
echo "Or if using GitHub integration, push to main branch:"
echo "  git push origin main"
echo ""
echo "✅ Setup instructions complete!"
echo ""
echo "To verify your production setup, run:"
echo "  node verify-production.js"